### ISSUE TITLE
Create a missing english translations check.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-translations#3]
Create a little script that builds a unique list of everything in `APIError::` , as well as the front end, and disjoint with the list of strings in `en.json`.

**Comment by shilangyu** [comment]
I actually created such a little script for extracting strings from `ApiError::` calls because I needed it for lemmur. It's not very robust yet so will share it once it is. 

In the meantime, it found that the `not_a_mod_or_admin` string exists in `lemmy` but not in `lemmy-translations`. Proof:

![image](https://user-images.githubusercontent.com/29288116/109433365-3f009400-7a10-11eb-8678-f6d4c4f48004.png)

**Comment by dessalines** [comment]
Sweet! Ya that would actually be really helpful. I'll add that one too.

**Comment by shilangyu** [comment]
I've been thinking, instead of creating such a script (which could not give a 100% guarantee anyways) it would probably make sense to codegen the keys as js/rust constants and use those instead. Would give some compile time guarantees that the i18n string actually exists.

And since you are using ts, on lemmy-ui ends it could be solved just by generating a union type of all i18n keys and constraining `i18n.t()` to those keys. Therefore it wouldn't require any refactoring. Will send a proof-of-concept PR to lemmy-ui.
